# Generated by Django 3.2.5 on 2021-08-02 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orgs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_name', models.CharField(max_length=90)),
                ('org_guid', models.CharField(max_length=90)),
                ('check_enabled', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Spaces',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('space_name', models.CharField(max_length=90)),
                ('space_guid', models.CharField(max_length=90, unique=True)),
                ('check_enabled', models.BooleanField(default=True)),
                ('orgs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.orgs')),
            ],
        ),
        migrations.CreateModel(
            name='Applications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(max_length=90)),
                ('budget', models.IntegerField()),
                ('budget_left', models.IntegerField()),
                ('budget_reset_date', models.DateTimeField()),
                ('spaces', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.spaces')),
            ],
        ),
    ]
